import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import styles from "./layout.module.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <header className={styles.header}>
                    Demo Note App
                    <nav className={styles.nav}>
                        <Link href="/products/women">여성옷</Link>
                        <Link href="/products/man">남성옷</Link>
                    </nav>
                </header>

                {children}
            </body>
        </html>
    );
}
