import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className={styles.header}>
                    Demo Note App
                    <nav className={styles.nav}>
                        <a>Contact</a>
                        <a>About</a>
                    </nav>
                </header>

                {children}
            </body>
        </html>
    );
}
